version: "3"  

tasks:
  default:
    cmds:
      - task: start

  start:
    cmds:
      - cmd: go run ./cmd/gophermart
        ignore_error: true

  test:
    cmds:
      - go build -o ./cmd/gophermart/gophermart ./cmd/gophermart/main.go
      - ./bin/gophermarttest -test.v -test.run='^TestGophermart$' -gophermart-binary-path=cmd/gophermart/gophermart -gophermart-host=localhost -gophermart-port=8080 -gophermart-database-uri="postgres://postgres:docker@localhost:5432/video" -accrual-binary-path=cmd/accrual/accrual_darwin_arm64 -accrual-host=localhost -accrual-port=8081 -accrual-database-uri="postgres://postgres:docker@localhost:5432/video"